{
 "title": "Api Gateway Merchant Handle - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Merchant Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindAll\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindById\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - FindAllActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindAllActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - FindAllActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindAllActive\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindAllActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - FindAllTrashed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindAllTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - FindAllTrashed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindAllTrashed\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindAllTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - Create",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"Create\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - Create",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"Create\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"Create\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - Update",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"Update\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - Update",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"Update\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"Update\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - UpdateStatus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"UpdateStatus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - UpdateStatus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"UpdateStatus\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"UpdateStatus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - TrashedMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"TrashedMerchant\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - TrashedMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"TrashedMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"TrashedMerchant\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - RestoreMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"RestoreMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - RestoreMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"RestoreMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"RestoreMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"Delete\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"Delete\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"Delete\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - RestoreAllMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"RestoreAllMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - RestoreAllMerchant",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"RestoreAllMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"RestoreAllMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Merchant Handle - DeleteAllMerchantPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"DeleteAllMerchantPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Merchant Handle - DeleteAllMerchantPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"DeleteAllMerchantPermanent\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"DeleteAllMerchantPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}