{
 "title": "Api Gateway Merchant Handle(Analytics & Reports Amount & Methods) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyPaymentMethodsMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyPaymentMethodsMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyPaymentMethodsMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyPaymentMethodsMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyPaymentMethodsMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyPaymentMethodMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyPaymentMethodMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyPaymentMethodMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyPaymentMethodMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyPaymentMethodMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTotalAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyTotalAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTotalAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyTotalAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyTotalAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTotalAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyTotalAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTotalAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyTotalAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyTotalAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}