{
 "title": "Api Gateway Merchant Handle By Merchant (Analytics & Reports Amount & Methods) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyPaymentMethodByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyPaymentMethodByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyPaymentMethodByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyPaymentMethodByMerchants\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyPaymentMethodByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyAmountMerchant",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyAmountMerchant\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyAmountMerchant\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyAmountByMerchants\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTotalAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyTotalAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTotalAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyTotalAmountByMerchants\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyTotalAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTotalAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyTotalAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTotalAmountByMerchants",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyTotalAmountByMerchants\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyTotalAmountByMerchants\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}