{
 "title": "Api Gateway Merchant Handle By ApiKey (Analytics & Reports Amount & Methods) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyPaymentMethodByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyPaymentMethodByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyPaymentMethodByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyPaymentMethodByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyPaymentMethodByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyPaymentMethodByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyPaymentMethodByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyPaymentMethodByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyPaymentMethodByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyPaymentMethodByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyAmountByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyAmountByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTotalAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindMonthlyTotalAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTotalAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindMonthlyTotalAmountByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindMonthlyTotalAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_requests_total{method=\"FindYearlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyAmountByApikeys",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(merchant_handler_request_duration_seconds_sum{method=\"FindYearlyAmountByApikeys\"}[1m]) \n/\nrate(merchant_handler_request_duration_seconds_count{method=\"FindYearlyAmountByApikeys\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}