{
 "title": "Api Gateway MerchantDocument Handle - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"FindAll\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"FindById\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - FindAllActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"FindAllActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - FindAllActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"FindAllActive\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"FindAllActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - FindAllTrashed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"FindAllTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - FindAllTrashed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"FindAllTrashed\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"FindAllTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - Create",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"Create\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - Create",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"Create\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"Create\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - Update",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"Update\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - Update",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"Update\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"Update\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - UpdateStatus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"UpdateStatus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - UpdateStatus",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"UpdateStatus\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"UpdateStatus\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - TrashedDocument",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"TrashedDocument\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - TrashedDocument",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"TrashedDocument\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"TrashedDocument\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - RestoreDocument",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"RestoreDocument\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - RestoreDocument",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"RestoreDocument\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"RestoreDocument\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"Delete\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - Delete",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"Delete\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"Delete\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - RestoreAllDocuments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"RestoreAllDocuments\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - RestoreAllDocuments",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"RestoreAllDocuments\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"RestoreAllDocuments\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata MerchantDocument Handle - DeleteAllDocumentsPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_requests_total{method=\"DeleteAllDocumentsPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata MerchantDocument Handle - DeleteAllDocumentsPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "rate(merchant_document_handler_request_duration_seconds_sum{method=\"DeleteAllDocumentsPermanent\"}[1m]) \n/\nrate(merchant_document_handler_request_duration_seconds_count{method=\"DeleteAllDocumentsPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}