{
 "title": "Api Gateway Card Handle(Analytics & Reports Withdraw) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyWithdrawAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyWithdrawAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyWithdrawAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyWithdrawAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyWithdrawAmount\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyWithdrawAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyWithdrawAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyWithdrawAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyWithdrawAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyWithdrawAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyWithdrawAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyWithdrawAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyWithdrawAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyWithdrawAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyWithdrawAmountByCardNumber\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyWithdrawAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyWithdrawAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyWithdrawAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyWithdrawAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyWithdrawAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}