{
 "title": "Api Gateway Card Handle(Analytics & Reports Topup) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTopupAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyTopupAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTopupAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyTopupAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyTopupAmount\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTopupAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyTopupAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTopupAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyTopupAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyTopupAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTopupAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyTopupAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTopupAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyTopupAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyTopupAmountByCardNumber\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTopupAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyTopupAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTopupAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyTopupAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyTopupAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}