{
 "title": "Api Gateway Card Handle(Analytics & Reports Balance) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyBalance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyBalance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyBalance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyBalance\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyBalance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyBalance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyBalance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyBalance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyBalance\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyBalance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyBalanceByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyBalanceByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyBalanceByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyBalanceByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyBalanceByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyBalanceByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyBalanceByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyBalanceByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyBalanceByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyBalanceByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}