{
 "title": "Api Gateway Card Handle (Core Operations) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindAll",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindAll\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindAll\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindByActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindByActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindByActive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindByActive\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindByActive\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindByTrashed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindByTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindByTrashed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindByTrashed\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindByTrashed\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindByUserID",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindByUserID\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindByUserID\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindByUserID",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindByUserID\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindById",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindById\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindById\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - CreateCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"CreateCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - CreateCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"CreateCard\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"CreateCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - UpdateCard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"UpdateCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - UpdateCard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"UpdateCard\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"UpdateCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - DeleteCardPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"DeleteCardPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - DeleteCardPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"DeleteCardPermanent\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"DeleteCardPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - TrashedCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"TrashedCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - TrashedCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"TrashedCard\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"TrashedCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - RestoreCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"RestoreCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - RestoreCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"RestoreCard\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"RestoreCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - RestoreAllCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"RestoreAllCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - RestoreAllCard",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"RestoreAllCard\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"RestoreAllCard\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - DeleteAllCardPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"DeleteAllCardPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - DeleteAllCardPermanent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"DeleteAllCardPermanent\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"DeleteAllCardPermanent\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}