{
 "title": "Api Gateway Card Handle(Analytics & Reports Transaction) - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTransactionAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyTransactionAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTransactionAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyTransactionAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyTransactionAmount\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTransactionAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyTransactionAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTransactionAmount",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyTransactionAmount\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyTransactionAmount\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindMonthlyTransactionAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindMonthlyTransactionAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindMonthlyTransactionAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindMonthlyTransactionAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindMonthlyTransactionAmountByCardNumber\"}[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Card Handle - FindYearlyTransactionAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_requests_total{method=\"FindYearlyTransactionAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Card Handle - FindYearlyTransactionAmountByCardNumber",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(card_handler_request_duration_seconds_sum{method=\"FindYearlyTransactionAmountByCardNumber\"}[1m]) \n/\nrate(card_handler_request_duration_seconds_count{method=\"FindYearlyTransactionAmountByCardNumber\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}