{
 "title": "Transfer Service",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Memory Off Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_other_sys_bytes{application=\"Transfer Service\"} - go_memstats_other_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_next_gc_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory In Heap",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_heap_released_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory In Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{application=\"Transfer Service\"} - go_memstats_frees_total{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{application=\"Transfer Service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "go_goroutines{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{application=\"Transfer Service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}