{
 "title": "Service Log Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Api Gateway  Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"apigateway\", filename=\"/var/log/app/apigateway.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Auth Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"auth-service\", filename=\"/var/log/app/auth-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Card Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"card-service\", filename=\"/var/log/app/card-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Email Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"email-service\", filename=\"/var/log/app/email-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Merchant Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"merchant-service\", filename=\"/var/log/app/merchant-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Role Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"role-service\", filename=\"/var/log/app/role-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Saldo Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"saldo-service\", filename=\"/var/log/app/saldo-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Topup Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"topup-service\", filename=\"/var/log/app/topup-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Transaction Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"transaction-service\", filename=\"/var/log/app/transaction-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Transfer Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"transfer-service\", filename=\"/var/log/app/transfer-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "User Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"user-service\", filename=\"/var/log/app/user-service.log\"}[1m])"
    }
   ]
  },
  {
   "title": "Withdraw Service Log Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"withdraw-service\", filename=\"/var/log/app/withdraw-service.log\"}[1m])"
    }
   ]
  }
 ]
}