{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Api Gateway",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apigateway\", filename=\"/var/log/app/apigateway.log\"}"
    }
   ]
  },
  {
   "title": "Auth Service Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"auth-service\", filename=\"/var/log/app/auth-service.log\"}"
    }
   ]
  },
  {
   "title": "Card Service logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"card-service\", filename=\"/var/log/app/card-service.log\"}"
    }
   ]
  },
  {
   "title": "Email Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"email-service\", filename=\"/var/log/app/email-service.log\"}"
    }
   ]
  },
  {
   "title": "Merchant Service logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"merchant-service\", filename=\"/var/log/app/merchant-service.log\"}"
    }
   ]
  },
  {
   "title": "Role Service logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"role-service\", filename=\"/var/log/app/role-service.log\"}\n"
    }
   ]
  },
  {
   "title": "Saldo Service logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"saldo-service\", filename=\"/var/log/app/saldo-service.log\"}"
    }
   ]
  },
  {
   "title": "Topup Service",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"topup-service\", filename=\"/var/log/app/topup-service.log\"}\n"
    }
   ]
  },
  {
   "title": "Transaction Service logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"transaction-service\", filename=\"/var/log/app/transaction-service.log\"}\n"
    }
   ]
  },
  {
   "title": "Transfer Service logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"transfer-service\", filename=\"/var/log/app/transfer-service.log\"}"
    }
   ]
  },
  {
   "title": "Withdraw",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"withdraw-service\", filename=\"/var/log/app/withdraw-service.log\"}"
    }
   ]
  },
  {
   "title": "User Service logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"user-service\", filename=\"/var/log/app/user-service.log\"}\n"
    }
   ]
  }
 ]
}