{
 "title": "Api Gateway Auth Handle - Metrics",
 "tags": [
  "Metrics",
  "ApiGateway"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(auth_handler_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate(auth_handler_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate per Handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(auth_handler_requests_total{status=\"error\"}[1m]))\n/\nsum(rate(auth_handler_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate per Handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(handler) (rate(auth_service_requests_total{status=\"success\"}[5m]))\n/\nsum by(handler) (rate(auth_service_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(auth_handler_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(auth_handler_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(auth_handler_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Handlers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(auth_handler_requests_total[1m])) by (method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - Login",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"Login\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"Login\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - Login",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"Login\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - Register",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"Register\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - Register",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"Register\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"Register\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - ForgotPassword",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"ForgotPassword\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - ForgotPassword",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"ForgotPassword\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"ForgotPassword\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - ResetPassword",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"ResetPassword\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - ResetPassword",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"ResetPassword\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"ResetPassword\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - RefreshToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"RefreshToken\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - RefreshToken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"RefreshToken\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"RefreshToken\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - GetMe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"GetMe\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - GetMe",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"GetMe\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"GetMe\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafik Rata Rata Auth Handle - VerifyCode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(auth_handler_requests_total{method=\"VerifyCode\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Durasi Rata Rata Auth Handle - VerifyCode",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(auth_handler_request_duration_seconds_sum{method=\"VerifyCode\"}[1m]) \n/\nrate(auth_handler_request_duration_seconds_count{method=\"VerifyCode\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}